version: '3.2'

services:
  web:
    image: '${IMAGE}'
    restart: always
    networks:
      - web
    environment:
      VIRTUAL_HOST: '${HOST}'
      LETSENCRYPT_HOST: '${HOST}'
      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'

networks:
  web:
    external: true
