name: Build & Deploy

on:
  push:
    branches:
      - master

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/momence:${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push web
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
    steps:
      - uses: actions/checkout@v3
      - name: Prepare .env
        working-directory: ./deploy
        run: envsubst < .env.production > .env
      - name: rsync deploy folder
        uses: up9cloud/action-rsync@v1.3
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USER: ${{ secrets.DEPLOY_USER }}
          KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          SOURCE: ./deploy/
          TARGET: ~/www/momence_${{ github.ref_name }}
          ARGS_MORE: --exclude=/vhost.d/
      - name: rsync nginx/vhost.d
        uses: up9cloud/action-rsync@v1.3
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USER: ${{ secrets.DEPLOY_USER }}
          KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          SOURCE: ./deploy/vhost.d/
          TARGET: ~/nginx/vhost.d
          ARGS: -avz
      - name: Update with Docker Compose
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          script: |
            echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            cd ~/www/momence_${{ github.ref_name }}
            docker compose pull
            docker compose down --remove-orphans
            docker compose up -d
